### PR TITLE
Some typos fixed, plus dim of matrix + adding a missing word.

### PR DESCRIPTION
**Pull request by federicomarini**
Hi @al2na,

As in the title:

- Some typos fixed
- Corrected dimension of matrix
- Adding a missing word
- added a space

As general comments:
- you might want to update the installation procedure of Bioconductor, which is described as via "a specific installer script", while now it uses (as you show in the code) via the `BiocManager` package
- maybe point out that `stringsAsFactors` might not be an issue anymore, at least with R >= 4.0.0
- line 359 of chapter 2: `df.f=d(enhancerFilePath, header = FALSE,data.table=FALSE)`, is `d` exported by `data.table` or was this meant to be `fread`?

Thank you for putting this nice book also available online!
Hope the fixes can help you 😉 
Federico

### CODE REVIEW

**Comment by federicomarini** [comment]
Another couple of things:

- Section 5.3: every row is actually a gene, and 1 patient is 1 column - the text does not match the shape of the `gexp`
- 5.8.2.2 - k seems to be 4 rather than 5, and number should be 100 instead of 20?
- 5.13.1 lambda seems to be 0.1, not 1?
- 5.14.4 - accuracy is not really 1, so it should not read "perfect"?
- 7.1: "Each of the 4 lines will represent a read" can be misleading, as a read is defined by the 4 lines as a whole

**Comment by federicomarini** [comment]
Re: the PCA plots done without `plotPCA` - the aspect ratio should be as specified in https://dx.doi.org/10.1371%2Fjournal.pcbi.1006907 - tip 6

**Comment by federicomarini** [comment]
After finishing up reading, I'd have a couple of additional remarks, I hope you find these useful

- 8.3.4: I'm not so sure what is discussed here is the "within sample" normalization, but rather the "between sample", i.e. the one that allows to compare different samples for the DE steps
- chapter 9: the Teng and Irizarry reference is there twice (one for the preprint, one for the published ms)
- 9.5.6.2: It is advisable to use `seqlevelsStyle` instead of just adding "chr", the former handles the cases where the conversion is not just done by pasting the string ahead (thinking of MT -> chrM) - Again also in the peak calling 9.6 section
- 9.7, I think the width should be either 100 if one wants the +/- 50, or the +/- part should be changed to +/-25
- Bibliography: 
  - Li and Durbin 2009 are present twice
  - Chen and Negre 2012a&b
  - Langmead & Salzber, 2012a&b
  - Stadler, Murr... 2011a&b

**Comment by al2na** [comment]
here merged!! :)

**Comment by al2na** [comment]
now I have to figure out how to recompile the book after all these years :)

**Comment by federicomarini** [comment]
Switching to a quarto book could possible be even the fastest solution, given their recent developments (and also the best long term one...)
Glad I could help on this!
F

**Pull request merged**
